version: "3.8"
services:
  tenpo-rest-api-percentage:
    container_name: tenpo-rest-api-percentage
    build:
      context: tenpo-rest-api-percentage
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./tenpo-rest-api-percentage:/app
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
      SPRING_JPA_DATABASE_PLATFORM: 'org.hibernate.dialect.PostgreSQLDialect'
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/TENPO_API_REST_SUM"
      SPRING_DATASOURCE_USERNAME: "tenpo"
      SPRING_DATASOURCE_PASSWORD: "tenpo2023"
      SERVER_PORT: "8082"
    depends_on:
      - db
  tenpo-rest-api-sum:
    container_name: tenpo-rest-api-sum
    build:
      context: tenpo-rest-api-sum
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./tenpo-rest-api-sum:/app
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: 'org.postgresql.Driver'
      SPRING_JPA_DATABASE_PLATFORM: 'org.hibernate.dialect.PostgreSQLDialect'
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: "1.0.0.0"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/TENPO_API_REST_SUM"
      SPRING_DATASOURCE_USERNAME: "tenpo"
      SPRING_DATASOURCE_PASSWORD: "tenpo2023"
      SERVER_PORT: "8081"
      PARAMETER_ENDPOINT_PARAMETERIZED_PERCENTAGE: "http://localhost:8081/api/percentage/"
      REDIS_HOSTNAME: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - .data:/var/lib/postgres
    environment:
      POSTGRES_DB: "TENPO_API_REST_SUM"
      POSTGRES_USER: "tenpo"
      POSTGRES_PASSWORD: "tenpo2023"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - .data:/var/lib/redis
    ports:
      - "6379:6379"
    depends_on:
      - pgadmin
