spring:
  application:
    name: tenpo-rest-api-percentage
  datasource:
    url: jdbc:postgresql://localhost:5432/TENPO_API_REST_SUM
    username: tenpo
    password: tenpo2023
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher