CREATE SEQUENCE public.CALLS_HISTORY_SEQ START 1;

CREATE TABLE public.CALLS_HISTORY(
CALLS_HISTORY_ID INT NOT null default nextval('CALLS_HISTORY_SEQ'),
REQUEST TEXT,
RESPONSE TEXT,
DATE_AND_HOUR TIMESTAMP,
PRIMARY KEY(CALLS_HISTORY_ID)
);